language: python
python:
    - "2.7"
env:
    - APP_SETTINGS="config.TestingConfig" DATABASE_URL="postgresql://localhost:5432/flashy_dev" TEST_DATABASE_URL="postgresql://localhost:5432/flashy_test"
services:
    - postgresql
install:
    - pip install -r requirements.txt
before_script:
    - psql -c 'create database flashy_test;' -U postgres
script:
    - nosetests -v