"""empty message

Revision ID: 6236d38bc7a9
Revises: dadf072a2b9f
Create Date: 2017-11-05 17:46:35.085781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6236d38bc7a9'
down_revision = 'dadf072a2b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'card', sa.Column('deck_id', sa.String(length=32), nullable=True))
    op.create_foreign_key(None, 'card', 'deck', ['deck_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column(u'card', 'deck_id')
    op.drop_table('deck')
    # ### end Alembic commands ###
